# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    sword_exception_listener:
        class: AppBundle\EventListener\SwordExceptionListener
        arguments: ["@templating"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException } 

    blackwhitelist:
        class: AppBundle\Services\BlackWhitelist
        arguments: ["@doctrine"]

    dtdvalidator:
        class: AppBundle\Services\DtdValidator

    virus_scanner:
        class: AppBundle\Services\VirusScanner
        arguments: ["%clamdscan_path%"]

