# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    sword_exception_listener:
        class: AppBundle\EventListener\SwordExceptionListener
        calls: 
            - [ setLogger, ["@monolog.logger.sword"]]
            - [ setTemplating, ["@templating"]]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException } 

    blackwhitelist:
        class: AppBundle\Services\BlackWhitelist
        arguments: ["@doctrine"]

    depositbuilder:
        class: AppBundle\Services\DepositBuilder
        calls:
            - [ setManager, ["@doctrine"]]
            - [ setLogger, ["@monolog.logger"]]
            - [ setRouter, ["@router"]]

    journalbuilder:
        class: AppBundle\Services\JournalBuilder
        calls:
            - [ setManager, ["@doctrine"]]
            - [ setLogger, ["@monolog.logger"]]
            - [ setRouter, ["@router"]]

    dtdvalidator:
        class: AppBundle\Services\DtdValidator

    virus_scanner:
        class: AppBundle\Services\VirusScanner
        arguments: ["%clamdscan_path%"]
        
    sword_client:
        class: AppBundle\Services\SwordClient
        arguments: ["%lockssomatic_sd_iri%", "%staging_server_uri%", "%staging_server_uuid%"]
        calls:
            - [ setLogger, ["@monolog.logger.sword"]]
            - [ setTemplating, ["@templating"]]
            - [ setRouter, ["@router"]]

    twig.extension.pcre:
        class: Jasny\Twig\PcreExtension
        tags:
            - { name: twig.extension }

    terms_of_use_listener:
        class: AppBundle\EventListener\TermsOfUseListener
        calls:
            - [ setLogger, ["@monolog.logger" ]]
            - [ setTokenStorage, ["@security.token_storage" ]]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: preRemove }
